"""empty message

Revision ID: 10704f4e8bbb
Revises: 93451ac17dd4
Create Date: 2020-08-19 11:45:59.308442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10704f4e8bbb'
down_revision = '93451ac17dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_private', sa.String(), nullable=True))
    op.drop_column('channels', 'isPrivate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('isPrivate', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('channels', 'is_private')
    # ### end Alembic commands ###
