"""empty message

Revision ID: 89ca1019afcd
Revises: ee29be4fba15
Create Date: 2020-11-25 16:18:34.601891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ca1019afcd'
down_revision = 'ee29be4fba15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('org_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'messages', 'orgs', ['org_id'], ['org_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'org_id')
    # ### end Alembic commands ###
