"""empty message

Revision ID: 93451ac17dd4
Revises: a9cbeba96d46
Create Date: 2020-08-19 11:18:14.188910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93451ac17dd4'
down_revision = 'a9cbeba96d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('admin_username', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('isPrivate', sa.String(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['admin_username'], ['username'])
    op.drop_column('channels', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('admin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'isPrivate')
    op.drop_column('channels', 'admin_username')
    # ### end Alembic commands ###
