"""empty message

Revision ID: da37e3bc2d5c
Revises: f86f94344d6f
Create Date: 2020-10-25 13:04:27.494069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da37e3bc2d5c'
down_revision = 'f86f94344d6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invites',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('responded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('invite_id')
    )
    op.create_foreign_key(None, 'channels', 'users', ['admin_username'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_table('org_invites')
    # ### end Alembic commands ###
