"""empty message

Revision ID: df91262a1099
Revises: c01d3b99a90b
Create Date: 2020-06-27 17:22:00.383479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df91262a1099'
down_revision = 'c01d3b99a90b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.create_table('cars',
    sa.Column('car_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('make', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('car_id', name='cars_pkey')
    )
    # ### end Alembic commands ###
