"""empty message

Revision ID: f86f94344d6f
Revises: ee29be4fba15
Create Date: 2020-10-21 10:29:21.440816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86f94344d6f'
down_revision = 'ee29be4fba15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_invites',
    sa.Column('invite_id', sa.Integer(), nullable=False),
    sa.Column('inviter_id', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('responded', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['inviter_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.org_id'], ),
    sa.PrimaryKeyConstraint('invite_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('org_invites')
    # ### end Alembic commands ###
