"""Added nickname to User model.

Revision ID: 360cb6152928
Revises: 773cef2a0499
Create Date: 2020-06-02 18:58:49.084834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360cb6152928'
down_revision = '773cef2a0499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
