"""New model added

Revision ID: 549fd4d92f55
Revises: 59d56223ef78
Create Date: 2020-06-16 21:46:08.620264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549fd4d92f55'
down_revision = '59d56223ef78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge',
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('challenge_user', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('challenge_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challenge')
    # ### end Alembic commands ###
