"""Removed nickname from User model.

Revision ID: 59d56223ef78
Revises: 360cb6152928
Create Date: 2020-06-02 19:06:58.980114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59d56223ef78'
down_revision = '360cb6152928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
