"""empty message

Revision ID: 7b7932c0b31d
Revises: 44ac3f2aa0c0
Create Date: 2020-09-14 13:27:43.025221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b7932c0b31d'
down_revision = '44ac3f2aa0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('admin_username', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'channels', 'users', ['admin_username'], ['username'])
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_constraint(None, 'channels', type_='foreignkey')
    op.drop_column('channels', 'is_private')
    op.drop_column('channels', 'admin_username')
    # ### end Alembic commands ###
