"""Trying to add rest of initial models and tables.

Revision ID: f7e61a377eb3
Revises: 65ee1f037ba9
Create Date: 2020-05-30 14:12:57.117562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e61a377eb3'
down_revision = '65ee1f037ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('channel_subscriptions',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_table('channel_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.channel_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('private_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['user_id'])
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_user_id_fkey', 'messages', 'users', ['user_id'], ['user_id'])
    op.drop_column('messages', 'sender_id')
    op.drop_table('private_messages')
    op.drop_table('channel_messages')
    op.drop_table('channel_subscriptions')
    op.drop_table('channels')
    # ### end Alembic commands ###
